### ISSUE TITLE
Collapsing all modules

### ISSUE THREAD

**Issue by jimmy3142** [idoavrah/terraform-tui#14]
Is is possible to collapse all modules?

**Comment by cedric-tw** [comment]
This would be great, or at least have a flag to collapse all modules by default, or only extend modules if they contain other modules to show the nesting. So many options 😉

**Comment by idoavrah** [comment]
![image](https://github.com/idoavrah/terraform-tui/assets/40628873/d7b65194-8c52-4327-924d-dfa57e2f210c)

**Comment by cedricbastin** [comment]
❤️ this is such a neater implementation than a CLI argument, thanks a lot!!

**Comment by jimmy3142** [comment]
I agree, great implementation! Thanks
