### ISSUE TITLE
Terragrunt support

### ISSUE THREAD

**Issue by Latyn4ik** [idoavrah/terraform-tui#15]
Are you planning to add Terragrunt support?

**Comment by idoavrah** [comment]
I'm not a Terragrunt user myself, so I can't say if I'll get to that in the foreseeable future.
If we add it to our repertoire later on (at work, that is), I'll definitely consider it.

**Comment by ErezWeiss** [comment]
At the moment I change all the terraform commands in the main (3 places) to terragrunt.
built with:
1. edit the version in pyproject.toml
2. run pip install build
3. run python -m build
4. run pip install ./dist/tftui-1.0.0.tar.gz (with your version)

good luck

**Comment by bkrein-vertex** [comment]
Perhaps adding a flag to toggle it to use `terragrunt` instead of `terraform` would be an easy permanent fix?  `tftui -T` or something?

**Comment by jonwtech** [comment]
Submitted a PR for this: https://github.com/idoavrah/terraform-tui/pull/30

**Comment by idoavrah** [comment]
Released version 0.5 that adds support for terragrunt (simply add/alias the '-e terragrunt' switch).

Thanks @jonwtech :)
