### ISSUE TITLE
add a brew formulae

### ISSUE THREAD

**Issue by idoavrah** [idoavrah/terraform-tui#17]

**Comment by cedricbastin** [comment]
`brew install tftui` instead of `pip install tftui`

**Comment by idoavrah** [comment]
> `brew install tftui` instead of `pip install tftui`

That's the general idea 😄

**Comment by Sanverik** [comment]
`* GitHub repository too new (<30 days old)` when I am trying to create a new formulae

**Comment by idoavrah** [comment]
![image](https://github.com/idoavrah/terraform-tui/assets/40628873/b268c80c-3e44-44fc-aaaa-cbd61a2a53c8)

**Comment by ganievs** [comment]
Hi guys! Might be a good idea to start with [homwbrew taps](https://docs.brew.sh/Taps)?

You need to create a repo for instance `terraform-tui-formula` with the homebrew formulae.

And installation through the tap will look like this. 
```bash
$ brew tap idoavrah/terraform-tui-formula
$ brew install terraform-tui
```

**Comment by idoavrah** [comment]
Done.

You can now install by running `brew install idoavrah/homebrew/tftui`.
