### ISSUE TITLE
tftui can't find terraform

### ISSUE THREAD

**Issue by sfederl** [idoavrah/terraform-tui#18]
Hi,

when i start tftui, i become a error.

`❯ tftui
Terraform not found. Please install Terraform and try again.`

Terraform is installed.
`❯ terraform -version
Terraform v1.4.6
on windows_amd64
+ provider registry.terraform.io/hashicorp/aws v4.65.0
+ provider registry.terraform.io/hashicorp/null v3.1.1

Your version of Terraform is out of date! The latest version
is 1.5.4. You can update by downloading from https://www.terraform.io/downloads.html`

i use Windows 11. How can set the terraform path in tftui?

**Comment by idoavrah** [comment]
Fixed, hopefully, in v0.4.1. Some nuance of the which command on Windows. 

If problem still persists on your machine, run ```where terraform``` and verify it is actually on the PATH environment variable.
