### ISSUE TITLE
Running tftui reporting "No state."

### ISSUE THREAD

**Issue by starzhanganz** [idoavrah/terraform-tui#21]
```
/Library/Python/3.9/bin/tftui test.tfstate                                                                              
No state.
```

how to import the statefile?

**Comment by idoavrah** [comment]
No need to import the state file, simply run the ```tftui``` command in the same directory you would run ```terraform plan``` in.

**Comment by spham** [comment]
hi, what happen when tfstate is on http backend in gitlab ?

**Comment by idoavrah** [comment]
TFTUI is agnostic to your backend choice. As long as you can run ```terraform state show``` and get results - it'll work seamlessly.
