### ISSUE TITLE
feature request: Disable auto init

### ISSUE THREAD

**Issue by Mykhailo-Roit** [idoavrah/terraform-tui#25]
some times I have TF config where init command is 
`terraform init --backend-config "${TFBACKEND_PATH}"`
So `terraform init` without this flag makes it impossible view tfstate

Could you add flag or config to disable terraform auto init?

**Comment by idoavrah** [comment]
Sounds simple enough, will do.

**Comment by idoavrah** [comment]
Published v0.4.2, check it out :)

**Comment by delaskoff** [comment]
Is it possible to set `init` to false by default? `init` is mostly a one-time action, so running it on every execution just delays the TUI from becoming ready for use, and specifying the `-no-init` flag for most executions doesn't sound reasonable

**Comment by delaskoff** [comment]
Even your own [comment](https://github.com/idoavrah/terraform-tui/issues/88#issuecomment-2992194360) proves this 😁 
> most developers use tftui to review an existing state, plan creation and application are few and far between
