### ISSUE TITLE
feature request: visualize existing tfstate file

### ISSUE THREAD

**Issue by Mykhailo-Roit** [idoavrah/terraform-tui#28]
only use `terraform show <someplanfile>` as input for visualize 

This file can create via
`terraform plan -out=<someplanfile>`

**Comment by idoavrah** [comment]
```tf show plan.out``` has an entirely different format (+/-). It will require a seperate parsing method. Also, the output is usually much smaller than the full state file.

Is there a real benefit in showing it in the TUI instead of viewing it on screen as a regular output?

**Comment by Mykhailo-Roit** [comment]
main goal is to visualize only planned changes
For big infra finding changes is quite difficult when using full state file

**Comment by Mykhailo-Roit** [comment]
and  **out file** can reduce a time for waiting because planning requires a lot of time for big infra

**Comment by idoavrah** [comment]
@Mykhailo-Roit plan and apply was added in v0.11.

Check it out.
