### ISSUE TITLE
Unable to update to the latest version

### ISSUE THREAD

**Issue by jimmy3142** [idoavrah/terraform-tui#66]
Hello!

I have previously installed terraform-tui  on my Mac using Homebrew. I am trying to upgrade to the latest version, and If I run `brew upgrade tftui`, my terminal returns this:
```
Warning: idoavrah/homebrew/tftui 0.13.0 already installed
```
and if I run `tftui --version`, it returns a different version:
```
tftui v0.4.2
```

Unfortunately, when I run the `tftui` command it shows the old UI:

![image](https://github.com/idoavrah/terraform-tui/assets/65279092/a3d04dab-5512-4b40-a221-c07061d6e2fa)

**Comment by idoavrah** [comment]
I almost forgot the app looked like this at one point :)

It looks like a local issue on your machine. 
Try running `which -a tftui` and see what you'll get. 
Maybe you've also installed `tftui` with pip in the global namespace? 

Report your findings here and we'll try to figure it out.

**Comment by jimmy3142** [comment]
haha, yeah the UI looks much better now!

Thanks. `which -a tftui` returns this:
```
/Users/james.watkins/.pyenv/shims/tftui
/opt/homebrew/bin/tftui
/opt/homebrew/bin/tftui
```
Looks like I originally installed tftui using pip. I have uninstalled it using `pip uninstall tftui`, and now I'm using the latest version that I have installed using homebrew 👍 

Thanks @idoavrah !
