### ISSUE TITLE
Feature Request - Offer an "offline" mode

### ISSUE THREAD

**Issue by b-per** [idoavrah/terraform-tui#67]
Even though I run `tftui` with the `-d` flag, in the background the CLI runs 2 HTTP requests:
- POST https://us-api.i.posthog.com/batch/
- GET https://pypi.org/pypi/tftui/json

It would be great to have a way to run the tool when behing a proxy with no access to the Internet

Also, I think that the `-d` flag should not send any POST to posthog. Is it a bug?

**Comment by idoavrah** [comment]
Hi Benoit,

The `-d` flag prevents the usage tracking, as advertised. It seems that simply importing the `posthog` module issues the POST request. I'll switch the import into a conditional one to prevent this from happening. I'll also make this flag render the application "offline" and prevent any outbound calls.

Thanks for bringing this to my attention, you can expect a new patched version sometime this week.

**Comment by idoavrah** [comment]
Just released v0.13.1 with the fix and an "offline" flag 😄
