### ISSUE TITLE
[Feature Request] Ability to display sensitives values

### ISSUE THREAD

**Issue by benriou** [idoavrah/terraform-tui#71]
Would it be possible to allow displaying sensitive values for a given object ? 

This could be allowed via a keystroke within the interface. 

Thanks !

**Comment by idoavrah** [comment]
The `terraform state show` command doesn't expose sensitive values. However, it seems that `terraform show -json` does expose them. Although there's no single-resource version for this command, meaning it will take some time to process, I think that would be acceptable.

I'll test it out and implement it if possible. Stay tuned :)

**Comment by idoavrah** [comment]
Done, I just released v0.13.2.
Hit `x` in the resource screen to expose the sensitive values. Enjoy 😄

**Comment by benriou** [comment]
Hello :) I just tested, it does not work :)
Pressing X on the resource screen does not change value displayed ( "sensitive value")

![CleanShot 2024-05-27 at 14 18 05@2x](https://github.com/idoavrah/terraform-tui/assets/40180297/d4677332-05fe-4396-805f-c1c23196bf95)

**Comment by idoavrah** [comment]
It works on my machine 😉 

I just noticed that it doesn't work with an uppercase 'X', could it be that your CAPS LOCK is on?

**Comment by idoavrah** [comment]
Found the problem. It didn't work on root resources, only inside modules.

Fixed in v0.13.3

**Comment by benriou** [comment]
It works perfectly. Thanks.
