### ISSUE TITLE
Support VIM-like navigation

### ISSUE THREAD

**Issue by fervic** [idoavrah/terraform-tui#77]
Hello! It would be nice to be able to also navigate up and down with the <kbd>J</kbd> and <kbd>K</kbd> keys respectively.

**Comment by idoavrah** [comment]
Sounds simple enough, will do.

**Comment by idoavrah** [comment]
> Awesome, thanks!
> Optionally, add <kbd>L</kbd> (right) to expand a tree.
> <kbd>H</kbd> (left) is already taken and should probably maintain its current function... Unless replaced by <kbd>?</kbd> 🤔 .
> 

That's exactly what I'm planning to do 😅

**Comment by idoavrah** [comment]
Done, enjoy the new version :)

**Comment by fervic** [comment]
> Done, enjoy the new version :)

Awesome, thank you!
