### ISSUE TITLE
Implement Resource Rename Functionality in Terraform UI

### ISSUE THREAD

**Issue by avisaradir** [idoavrah/terraform-tui#8]
**Issue Description:**
The Terraform CLI provides a `state mv` command to move resources between state files and rename them.

**Issue Details:**
The Terraform UI product should include a user-friendly feature to allow resource renaming, similar to the `state mv` command in the CLI. This enhancement would provide users with a seamless experience when managing resources, and it would ensure consistency between the state file and the configuration file.

Proposed Solution:
The proposed solution is to introduce a new feature in the Terraform UI that allows users to rename resources directly within the user interface. When a resource is renamed, the Terraform UI should automatically update the corresponding resource's name in the state file without modifying the underlying configuration file.

**Comment by idoavrah** [comment]
There's no option to rename resources/modules without changing the original configuration files. 
I can create a temporary "moved" block but it'll still require me to change the original TF files and I'm reluctant to do that.
